project_name: sommelier

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: "sommelier"
    main: ./cmd/sommelier/main.go
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sommelier -X github.com/cosmos/cosmos-sdk/version.AppName=sommelier -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  name_template: "Release {{.Version}}"

archives:
  - files:
    - LICENSE
    - README.md