#!/bin/bash

dev-env () {
  commands () {
    cat <<-EOF
dev-env commands:
  start -> start dev-env
  stop  -> stop dev-env
EOF
  }

  case $1 in
    start)
      read -r -p "You are about to delete ./data directory. ARE YOU SURE? [y/N] " response
      case "$response" in
          [yY][eE][sS]|[yY])
              echo "installing binaries..."
              make install > /dev/null 2>&1
              rm -rf ./data
              ./scripts/three-node.sh skip
              true
              ;;
          *)
              false
              ;;
      esac
      ;;
    stop)
      echo "stopping sommelier and feeder instances"
      pkill -9 sommelier
      pkill -9 oracle-feeder
      ;;
    *)
      commands
      ;;
  esac
}

dev-env $1 $2