// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: poa/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8bbf008d57591b4, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8bbf008d57591b4, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAuthoritySetRequest struct {
}

func (m *QueryAuthoritySetRequest) Reset()         { *m = QueryAuthoritySetRequest{} }
func (m *QueryAuthoritySetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuthoritySetRequest) ProtoMessage()    {}
func (*QueryAuthoritySetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8bbf008d57591b4, []int{2}
}
func (m *QueryAuthoritySetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuthoritySetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuthoritySetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuthoritySetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuthoritySetRequest.Merge(m, src)
}
func (m *QueryAuthoritySetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuthoritySetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuthoritySetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuthoritySetRequest proto.InternalMessageInfo

type QueryAuthoritySetResponse struct {
	Validators []string `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (m *QueryAuthoritySetResponse) Reset()         { *m = QueryAuthoritySetResponse{} }
func (m *QueryAuthoritySetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuthoritySetResponse) ProtoMessage()    {}
func (*QueryAuthoritySetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8bbf008d57591b4, []int{3}
}
func (m *QueryAuthoritySetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuthoritySetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuthoritySetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuthoritySetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuthoritySetResponse.Merge(m, src)
}
func (m *QueryAuthoritySetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuthoritySetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuthoritySetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuthoritySetResponse proto.InternalMessageInfo

func (m *QueryAuthoritySetResponse) GetValidators() []string {
	if m != nil {
		return m.Validators
	}
	return nil
}

type QueryEffectivePowerRequest struct {
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
}

func (m *QueryEffectivePowerRequest) Reset()         { *m = QueryEffectivePowerRequest{} }
func (m *QueryEffectivePowerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEffectivePowerRequest) ProtoMessage()    {}
func (*QueryEffectivePowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8bbf008d57591b4, []int{4}
}
func (m *QueryEffectivePowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEffectivePowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEffectivePowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEffectivePowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEffectivePowerRequest.Merge(m, src)
}
func (m *QueryEffectivePowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEffectivePowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEffectivePowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEffectivePowerRequest proto.InternalMessageInfo

func (m *QueryEffectivePowerRequest) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

type QueryEffectivePowerResponse struct {
	Power       int64 `protobuf:"varint,1,opt,name=power,proto3" json:"power,omitempty"`
	IsAuthority bool  `protobuf:"varint,2,opt,name=is_authority,json=isAuthority,proto3" json:"is_authority,omitempty"`
}

func (m *QueryEffectivePowerResponse) Reset()         { *m = QueryEffectivePowerResponse{} }
func (m *QueryEffectivePowerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEffectivePowerResponse) ProtoMessage()    {}
func (*QueryEffectivePowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8bbf008d57591b4, []int{5}
}
func (m *QueryEffectivePowerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEffectivePowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEffectivePowerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEffectivePowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEffectivePowerResponse.Merge(m, src)
}
func (m *QueryEffectivePowerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEffectivePowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEffectivePowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEffectivePowerResponse proto.InternalMessageInfo

func (m *QueryEffectivePowerResponse) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *QueryEffectivePowerResponse) GetIsAuthority() bool {
	if m != nil {
		return m.IsAuthority
	}
	return false
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "poa.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "poa.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAuthoritySetRequest)(nil), "poa.v1.QueryAuthoritySetRequest")
	proto.RegisterType((*QueryAuthoritySetResponse)(nil), "poa.v1.QueryAuthoritySetResponse")
	proto.RegisterType((*QueryEffectivePowerRequest)(nil), "poa.v1.QueryEffectivePowerRequest")
	proto.RegisterType((*QueryEffectivePowerResponse)(nil), "poa.v1.QueryEffectivePowerResponse")
}

func init() { proto.RegisterFile("poa/v1/query.proto", fileDescriptor_c8bbf008d57591b4) }

var fileDescriptor_c8bbf008d57591b4 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x6d, 0x56, 0x56, 0x31, 0x6f, 0x1a, 0xc8, 0xeb, 0xa1, 0x78, 0x28, 0x6b, 0xc3, 0x81, 0x22,
	0x50, 0xac, 0x0d, 0x84, 0x84, 0xe0, 0xb2, 0xa1, 0x89, 0xeb, 0x08, 0x12, 0x07, 0x2e, 0x95, 0xd7,
	0x7a, 0x99, 0x51, 0xdb, 0xcf, 0xb3, 0xdd, 0x40, 0x05, 0x5c, 0x10, 0x3f, 0x00, 0x89, 0x03, 0x7f,
	0x69, 0xc7, 0x49, 0x5c, 0x38, 0x21, 0xd4, 0xf2, 0x43, 0x50, 0x6c, 0x67, 0x6a, 0xd6, 0x68, 0x37,
	0xe7, 0xf9, 0x7d, 0xef, 0x3d, 0xbf, 0x4f, 0x41, 0x58, 0x02, 0xa3, 0xd9, 0x2e, 0x3d, 0x9b, 0x70,
	0x35, 0x8d, 0xa5, 0x02, 0x03, 0xb8, 0x21, 0x81, 0xc5, 0xd9, 0x2e, 0xb9, 0x9b, 0x02, 0xa4, 0x43,
	0x4e, 0x99, 0x14, 0x94, 0x8d, 0xc7, 0x60, 0x98, 0x11, 0x30, 0xd6, 0x8e, 0x45, 0x9a, 0x29, 0xa4,
	0x60, 0x8f, 0x34, 0x3f, 0x79, 0x74, 0xcb, 0xeb, 0x49, 0xa6, 0xd8, 0xc8, 0x53, 0xa3, 0x26, 0xc2,
	0xaf, 0x73, 0xfd, 0x23, 0x0b, 0x26, 0xfc, 0x6c, 0xc2, 0xb5, 0x89, 0x5e, 0xa2, 0xad, 0x12, 0xaa,
	0x25, 0x8c, 0x35, 0xc7, 0x8f, 0x50, 0xc3, 0x0d, 0xb7, 0x82, 0x76, 0xd0, 0x5d, 0xdf, 0xdb, 0x8c,
	0x5d, 0x9c, 0xd8, 0xf1, 0x0e, 0x6e, 0x9c, 0xff, 0xd9, 0xa9, 0x25, 0x9e, 0x13, 0x11, 0xd4, 0xb2,
	0x22, 0xfb, 0x13, 0x73, 0x0a, 0x4a, 0x98, 0xe9, 0x1b, 0x6e, 0x0a, 0x83, 0xe7, 0xe8, 0x4e, 0xc5,
	0x9d, 0xb7, 0x09, 0x11, 0xca, 0xd8, 0x50, 0x0c, 0x98, 0x01, 0x95, 0x5b, 0xd5, 0xbb, 0x6b, 0xc9,
	0x02, 0x12, 0xbd, 0x42, 0xc4, 0x0e, 0x1f, 0x9e, 0x9c, 0xf0, 0xbe, 0x11, 0x19, 0x3f, 0x82, 0x0f,
	0x5c, 0x79, 0x69, 0xfc, 0x00, 0xdd, 0x06, 0xc9, 0x55, 0x4e, 0xed, 0xb1, 0xc1, 0x40, 0x71, 0xed,
	0xe2, 0xae, 0x25, 0xb7, 0x0a, 0x7c, 0xdf, 0xc1, 0xd1, 0x5b, 0xb4, 0x5d, 0x29, 0xe4, 0x73, 0x34,
	0xd1, 0xaa, 0xcc, 0x01, 0x3b, 0x5e, 0x4f, 0xdc, 0x07, 0xee, 0xa0, 0x0d, 0xa1, 0x7b, 0xac, 0x08,
	0xde, 0x5a, 0x69, 0x07, 0xdd, 0x9b, 0xc9, 0xba, 0xd0, 0x97, 0x6f, 0xd9, 0xfb, 0x56, 0x47, 0xab,
	0x56, 0x18, 0xf7, 0x51, 0xc3, 0x75, 0x83, 0x49, 0xd1, 0xd5, 0x72, 0xdd, 0x64, 0xbb, 0xf2, 0xce,
	0xa5, 0x88, 0xda, 0x5f, 0x7f, 0xfd, 0xfb, 0xb1, 0x42, 0x70, 0x8b, 0x6a, 0x18, 0x8d, 0xf8, 0x50,
	0x70, 0x45, 0x4b, 0x9b, 0xc4, 0x9f, 0xd1, 0xc6, 0x62, 0x8f, 0xb8, 0x5d, 0x92, 0xab, 0xa8, 0x9f,
	0x74, 0xae, 0x61, 0x78, 0xdb, 0xfb, 0xd6, 0xb6, 0x83, 0x77, 0x96, 0x6d, 0x2f, 0xdf, 0xde, 0xd3,
	0xdc, 0xe0, 0x9f, 0x01, 0xda, 0x2c, 0x17, 0x88, 0xa3, 0x92, 0x7c, 0xe5, 0x9a, 0xc8, 0xbd, 0x6b,
	0x39, 0x3e, 0xc4, 0x0b, 0x1b, 0xe2, 0x29, 0x7e, 0xb2, 0x1c, 0x82, 0x17, 0x13, 0x3d, 0xbb, 0x16,
	0xfa, 0xe9, 0xea, 0xd2, 0xbf, 0x1c, 0x1c, 0x9e, 0xcf, 0xc2, 0xe0, 0x62, 0x16, 0x06, 0x7f, 0x67,
	0x61, 0xf0, 0x7d, 0x1e, 0xd6, 0x2e, 0xe6, 0x61, 0xed, 0xf7, 0x3c, 0xac, 0xbd, 0x7b, 0x98, 0x0a,
	0x73, 0x3a, 0x39, 0x8e, 0xfb, 0x30, 0xa2, 0x92, 0xa7, 0xe9, 0xf4, 0x7d, 0xb6, 0xe0, 0x90, 0x3d,
	0xa3, 0x1f, 0xad, 0x8d, 0x99, 0x4a, 0xae, 0x8f, 0x1b, 0xf6, 0x4f, 0x79, 0xfc, 0x3f, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0x6b, 0x07, 0x62, 0x90, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	AuthoritySet(ctx context.Context, in *QueryAuthoritySetRequest, opts ...grpc.CallOption) (*QueryAuthoritySetResponse, error)
	EffectivePower(ctx context.Context, in *QueryEffectivePowerRequest, opts ...grpc.CallOption) (*QueryEffectivePowerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/poa.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuthoritySet(ctx context.Context, in *QueryAuthoritySetRequest, opts ...grpc.CallOption) (*QueryAuthoritySetResponse, error) {
	out := new(QueryAuthoritySetResponse)
	err := c.cc.Invoke(ctx, "/poa.v1.Query/AuthoritySet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EffectivePower(ctx context.Context, in *QueryEffectivePowerRequest, opts ...grpc.CallOption) (*QueryEffectivePowerResponse, error) {
	out := new(QueryEffectivePowerResponse)
	err := c.cc.Invoke(ctx, "/poa.v1.Query/EffectivePower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	AuthoritySet(context.Context, *QueryAuthoritySetRequest) (*QueryAuthoritySetResponse, error)
	EffectivePower(context.Context, *QueryEffectivePowerRequest) (*QueryEffectivePowerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AuthoritySet(ctx context.Context, req *QueryAuthoritySetRequest) (*QueryAuthoritySetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthoritySet not implemented")
}
func (*UnimplementedQueryServer) EffectivePower(ctx context.Context, req *QueryEffectivePowerRequest) (*QueryEffectivePowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EffectivePower not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poa.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuthoritySet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuthoritySetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuthoritySet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poa.v1.Query/AuthoritySet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuthoritySet(ctx, req.(*QueryAuthoritySetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EffectivePower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEffectivePowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EffectivePower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poa.v1.Query/EffectivePower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EffectivePower(ctx, req.(*QueryEffectivePowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "poa.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AuthoritySet",
			Handler:    _Query_AuthoritySet_Handler,
		},
		{
			MethodName: "EffectivePower",
			Handler:    _Query_EffectivePower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poa/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAuthoritySetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuthoritySetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuthoritySetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAuthoritySetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuthoritySetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuthoritySetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Validators[iNdEx])
			copy(dAtA[i:], m.Validators[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Validators[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEffectivePowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEffectivePowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEffectivePowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEffectivePowerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEffectivePowerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEffectivePowerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsAuthority {
		i--
		if m.IsAuthority {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Power != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAuthoritySetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAuthoritySetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, s := range m.Validators {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryEffectivePowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEffectivePowerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Power != 0 {
		n += 1 + sovQuery(uint64(m.Power))
	}
	if m.IsAuthority {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuthoritySetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuthoritySetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuthoritySetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuthoritySetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuthoritySetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuthoritySetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEffectivePowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEffectivePowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEffectivePowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEffectivePowerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEffectivePowerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEffectivePowerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAuthority", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAuthority = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
