[package]
name = "somm_proto"
version = "5.0.0"
authors = ["PeggyJV"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.7"
prost-types = "0.7"
bytes = "1"
cosmos-sdk-proto = {git="http://github.com/cosmos/cosmos-rust", branch="main"}
tonic = "0.4"
serde = "1.0"
