// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: il/v1/il.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Stoploss defines a set of parameters that together trigger a stoploss withdrawal.
type Stoploss struct {
	// uniswap pair identifier
	UniswapPairId string `protobuf:"bytes,1,opt,name=uniswap_pair_id,json=uniswapPairId,proto3" json:"uniswap_pair_id,omitempty" yaml:"uniswap_pair"`
	// amount of shares from the liquidity pool to redeem if current slippage > max slipage
	LiquidityPoolShares int64 `protobuf:"varint,2,opt,name=liquidity_pool_shares,json=liquidityPoolShares,proto3" json:"liquidity_pool_shares,omitempty" yaml:"liquidity_pool_shares"`
	// max slippage allowed before the stoploss is triggered
	MaxSlippage github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=max_slippage,json=maxSlippage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_slippage" yaml:"max_slippage"`
	// starting token pair ration of the uniswap pool
	ReferencePairRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=reference_pair_ratio,json=referencePairRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reference_pair_ratio" yaml:"reference_pair_ratio"`
}

func (m *Stoploss) Reset()         { *m = Stoploss{} }
func (m *Stoploss) String() string { return proto.CompactTextString(m) }
func (*Stoploss) ProtoMessage()    {}
func (*Stoploss) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb151ade557e4dd, []int{0}
}
func (m *Stoploss) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stoploss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stoploss.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stoploss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stoploss.Merge(m, src)
}
func (m *Stoploss) XXX_Size() int {
	return m.Size()
}
func (m *Stoploss) XXX_DiscardUnknown() {
	xxx_messageInfo_Stoploss.DiscardUnknown(m)
}

var xxx_messageInfo_Stoploss proto.InternalMessageInfo

func (m *Stoploss) GetUniswapPairId() string {
	if m != nil {
		return m.UniswapPairId
	}
	return ""
}

func (m *Stoploss) GetLiquidityPoolShares() int64 {
	if m != nil {
		return m.LiquidityPoolShares
	}
	return 0
}

// Params define the impermanent loss module parameters
type Params struct {
	// contract address for impermanent loss handling on ethereum
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" yaml:"contract_address"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb151ade557e4dd, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Stoploss)(nil), "il.v1.Stoploss")
	proto.RegisterType((*Params)(nil), "il.v1.Params")
}

func init() { proto.RegisterFile("il/v1/il.proto", fileDescriptor_ccb151ade557e4dd) }

var fileDescriptor_ccb151ade557e4dd = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbd, 0xee, 0xd3, 0x30,
	0x14, 0xc5, 0x13, 0x0a, 0x7f, 0x81, 0xf9, 0x28, 0x4a, 0x8b, 0x1a, 0x51, 0x94, 0x54, 0x19, 0xa0,
	0x0b, 0xb1, 0x2a, 0x36, 0x16, 0xd4, 0x0a, 0x90, 0x18, 0x90, 0xa2, 0x94, 0x89, 0x25, 0x72, 0x13,
	0x93, 0x1a, 0xec, 0x5e, 0x63, 0xbb, 0xa5, 0x99, 0x78, 0x01, 0x06, 0x1e, 0xab, 0x63, 0x47, 0xc4,
	0x10, 0xa1, 0xf6, 0x0d, 0xfa, 0x04, 0xa8, 0x49, 0x28, 0x15, 0xea, 0xc2, 0x64, 0xdf, 0x9f, 0xaf,
	0xce, 0xf1, 0xb9, 0x36, 0xba, 0xc7, 0x38, 0x5e, 0x8d, 0x30, 0xe3, 0xa1, 0x54, 0x60, 0xc0, 0xb9,
	0xc1, 0x78, 0xb8, 0x1a, 0x3d, 0xec, 0xe6, 0x90, 0x43, 0x45, 0xf0, 0x71, 0x57, 0x1f, 0x06, 0xdf,
	0x5a, 0xe8, 0xe6, 0xd4, 0x80, 0xe4, 0xa0, 0xb5, 0xf3, 0x02, 0xb5, 0x97, 0x0b, 0xa6, 0xbf, 0x10,
	0x99, 0x48, 0xc2, 0x54, 0xc2, 0x32, 0xd7, 0x1e, 0xd8, 0xc3, 0x5b, 0x93, 0xde, 0xa1, 0xf4, 0x3b,
	0x05, 0x11, 0xfc, 0x79, 0x70, 0xde, 0x10, 0xc4, 0x77, 0x9b, 0x32, 0x22, 0x4c, 0xbd, 0xc9, 0x9c,
	0x77, 0xe8, 0x01, 0x67, 0x9f, 0x97, 0x2c, 0x63, 0xa6, 0x48, 0x24, 0x00, 0x4f, 0xf4, 0x9c, 0x28,
	0xaa, 0xdd, 0x6b, 0x03, 0x7b, 0xd8, 0x9a, 0x0c, 0x0e, 0xa5, 0xff, 0xa8, 0x96, 0xb9, 0xd8, 0x16,
	0xc4, 0x9d, 0x13, 0x8f, 0x00, 0xf8, 0xb4, 0xa2, 0xce, 0x1c, 0xdd, 0x11, 0x64, 0x9d, 0x68, 0xce,
	0xa4, 0x24, 0x39, 0x75, 0x5b, 0xd5, 0x9d, 0x5e, 0x6d, 0x4a, 0xdf, 0xfa, 0x59, 0xfa, 0x8f, 0x73,
	0x66, 0xe6, 0xcb, 0x59, 0x98, 0x82, 0xc0, 0x29, 0x68, 0x01, 0xba, 0x59, 0x9e, 0xea, 0xec, 0x13,
	0x36, 0x85, 0xa4, 0x3a, 0x7c, 0x49, 0xd3, 0xbf, 0x09, 0xce, 0xb5, 0x82, 0xf8, 0xb6, 0x20, 0xeb,
	0x69, 0x53, 0x39, 0x5f, 0x51, 0x57, 0xd1, 0x0f, 0x54, 0xd1, 0x45, 0x4a, 0xeb, 0x11, 0x28, 0x62,
	0x18, 0xb8, 0xd7, 0x2b, 0xc7, 0xb7, 0xff, 0xed, 0xd8, 0xaf, 0x1d, 0x2f, 0x69, 0x06, 0xb1, 0x73,
	0xc2, 0xc7, 0xe9, 0xc5, 0x15, 0x8c, 0xd0, 0x55, 0x44, 0x14, 0x11, 0xda, 0x79, 0x8d, 0xee, 0xa7,
	0xb0, 0x30, 0x8a, 0xa4, 0x26, 0x21, 0x59, 0xa6, 0xa8, 0xd6, 0xcd, 0x63, 0xf4, 0x0f, 0xa5, 0xdf,
	0xab, 0x85, 0xff, 0xed, 0x08, 0xe2, 0xf6, 0x1f, 0x34, 0xae, 0xc9, 0x64, 0xbc, 0xd9, 0x79, 0xf6,
	0x76, 0xe7, 0xd9, 0xbf, 0x76, 0x9e, 0xfd, 0x7d, 0xef, 0x59, 0xdb, 0xbd, 0x67, 0xfd, 0xd8, 0x7b,
	0xd6, 0xfb, 0x27, 0x67, 0x31, 0x24, 0xcd, 0xf3, 0xe2, 0xe3, 0x0a, 0x6b, 0x10, 0x82, 0x72, 0x46,
	0x15, 0x5e, 0x63, 0xc6, 0xeb, 0x2c, 0xb3, 0xab, 0xea, 0xab, 0x3c, 0xfb, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x42, 0xa1, 0xdb, 0xbf, 0x59, 0x02, 0x00, 0x00,
}

func (m *Stoploss) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stoploss) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stoploss) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ReferencePairRatio.Size()
		i -= size
		if _, err := m.ReferencePairRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIl(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MaxSlippage.Size()
		i -= size
		if _, err := m.MaxSlippage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIl(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.LiquidityPoolShares != 0 {
		i = encodeVarintIl(dAtA, i, uint64(m.LiquidityPoolShares))
		i--
		dAtA[i] = 0x10
	}
	if len(m.UniswapPairId) > 0 {
		i -= len(m.UniswapPairId)
		copy(dAtA[i:], m.UniswapPairId)
		i = encodeVarintIl(dAtA, i, uint64(len(m.UniswapPairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintIl(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIl(dAtA []byte, offset int, v uint64) int {
	offset -= sovIl(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Stoploss) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UniswapPairId)
	if l > 0 {
		n += 1 + l + sovIl(uint64(l))
	}
	if m.LiquidityPoolShares != 0 {
		n += 1 + sovIl(uint64(m.LiquidityPoolShares))
	}
	l = m.MaxSlippage.Size()
	n += 1 + l + sovIl(uint64(l))
	l = m.ReferencePairRatio.Size()
	n += 1 + l + sovIl(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovIl(uint64(l))
	}
	return n
}

func sovIl(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIl(x uint64) (n int) {
	return sovIl(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Stoploss) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stoploss: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stoploss: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniswapPairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniswapPairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityPoolShares", wireType)
			}
			m.LiquidityPoolShares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidityPoolShares |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSlippage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxSlippage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferencePairRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReferencePairRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthIl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthIl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIl(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIl
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIl
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIl
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIl
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIl        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIl          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIl = fmt.Errorf("proto: unexpected end of group")
)
