syntax = "proto3";
package poa.v1;

option go_package = "github.com/peggyjv/sommelier/v9/x/poa/types";

import "google/api/annotations.proto";
import "gogoproto/gogo.proto";
import "poa/v1/params.proto";

service Query {
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/sommelier/poa/v1/params";
  }
  rpc AuthoritySet(QueryAuthoritySetRequest) returns (QueryAuthoritySetResponse) {
    option (google.api.http).get = "/sommelier/poa/v1/authority_set";
  }
  rpc EffectivePower(QueryEffectivePowerRequest) returns (QueryEffectivePowerResponse) {
    option (google.api.http).get = "/sommelier/poa/v1/effective_power/{operator_address}";
  }
}

message QueryParamsRequest {}
message QueryParamsResponse {
  Params params = 1 [(gogoproto.nullable) = false];
}

message QueryAuthoritySetRequest {}
message QueryAuthoritySetResponse {
  repeated string validators = 1;
}

message QueryEffectivePowerRequest {
  string operator_address = 1;
}
message QueryEffectivePowerResponse {
  int64 power = 1;
  bool is_authority = 2;
}
