// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axelarcork/v1/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ScheduleCorkEvent struct {
	Signer      string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Validator   string `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Cork        string `protobuf:"bytes,3,opt,name=cork,proto3" json:"cork,omitempty"`
	BlockHeight uint64 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	ChainId     uint64 `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *ScheduleCorkEvent) Reset()         { *m = ScheduleCorkEvent{} }
func (m *ScheduleCorkEvent) String() string { return proto.CompactTextString(m) }
func (*ScheduleCorkEvent) ProtoMessage()    {}
func (*ScheduleCorkEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_568389573c9d22fd, []int{0}
}
func (m *ScheduleCorkEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleCorkEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleCorkEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleCorkEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleCorkEvent.Merge(m, src)
}
func (m *ScheduleCorkEvent) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleCorkEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleCorkEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleCorkEvent proto.InternalMessageInfo

func (m *ScheduleCorkEvent) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *ScheduleCorkEvent) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ScheduleCorkEvent) GetCork() string {
	if m != nil {
		return m.Cork
	}
	return ""
}

func (m *ScheduleCorkEvent) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ScheduleCorkEvent) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func init() {
	proto.RegisterType((*ScheduleCorkEvent)(nil), "axelarcork.v1.ScheduleCorkEvent")
}

func init() { proto.RegisterFile("axelarcork/v1/event.proto", fileDescriptor_568389573c9d22fd) }

var fileDescriptor_568389573c9d22fd = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x6b, 0x08, 0x85, 0x1a, 0x18, 0xb0, 0x10, 0x4a, 0x11, 0xb2, 0x0a, 0x53, 0xa7, 0x58,
	0x85, 0x81, 0x1d, 0x84, 0x04, 0x12, 0x53, 0xd9, 0x58, 0xaa, 0xfc, 0x39, 0x39, 0x26, 0x4e, 0x2e,
	0x72, 0x5c, 0xab, 0x7d, 0x0b, 0x76, 0x5e, 0x88, 0xb1, 0x23, 0x23, 0x4a, 0x5e, 0x04, 0xc5, 0x20,
	0x95, 0xed, 0xfb, 0x7e, 0x3f, 0xcb, 0xa7, 0x3b, 0x3a, 0x8e, 0x57, 0xa0, 0x63, 0x93, 0xa2, 0x29,
	0x84, 0x9b, 0x09, 0x70, 0x50, 0xd9, 0xa8, 0x36, 0x68, 0x91, 0x1d, 0x6f, 0x55, 0xe4, 0x66, 0xe7,
	0xa7, 0x12, 0x25, 0x7a, 0x23, 0xfa, 0xf4, 0xfb, 0xe8, 0xea, 0x83, 0xd0, 0x93, 0x97, 0x34, 0x87,
	0x6c, 0xa9, 0xe1, 0x1e, 0x4d, 0xf1, 0xd0, 0x7f, 0xc0, 0xce, 0xe8, 0xb0, 0x51, 0xb2, 0x02, 0x13,
	0x92, 0x09, 0x99, 0x8e, 0xe6, 0x7f, 0x8d, 0x5d, 0xd0, 0x91, 0x8b, 0xb5, 0xca, 0x62, 0x8b, 0x26,
	0xdc, 0xf1, 0x6a, 0x0b, 0x18, 0xa3, 0x41, 0x3f, 0x2c, 0xdc, 0xf5, 0xc2, 0x67, 0x76, 0x49, 0x8f,
	0x12, 0x8d, 0x69, 0xb1, 0xc8, 0x41, 0xc9, 0xdc, 0x86, 0xc1, 0x84, 0x4c, 0x83, 0xf9, 0xa1, 0x67,
	0x8f, 0x1e, 0xb1, 0x31, 0x3d, 0x48, 0xf3, 0x58, 0x55, 0x0b, 0x95, 0x85, 0x7b, 0x5e, 0xef, 0xfb,
	0xfe, 0x94, 0xdd, 0x3d, 0x7f, 0xb6, 0x9c, 0x6c, 0x5a, 0x4e, 0xbe, 0x5b, 0x4e, 0xde, 0x3b, 0x3e,
	0xd8, 0x74, 0x7c, 0xf0, 0xd5, 0xf1, 0xc1, 0xeb, 0xb5, 0x54, 0x36, 0x5f, 0x26, 0x51, 0x8a, 0xa5,
	0xa8, 0x41, 0xca, 0xf5, 0x9b, 0x13, 0x0d, 0x96, 0x25, 0x68, 0x05, 0x46, 0xb8, 0x5b, 0xb1, 0x12,
	0xff, 0x2e, 0x63, 0xd7, 0x35, 0x34, 0xc9, 0xd0, 0xaf, 0x7c, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x1a, 0x10, 0x35, 0x2f, 0x34, 0x01, 0x00, 0x00,
}

func (m *ScheduleCorkEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleCorkEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleCorkEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainId != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x28
	}
	if m.BlockHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Cork) > 0 {
		i -= len(m.Cork)
		copy(dAtA[i:], m.Cork)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Cork)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ScheduleCorkEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Cork)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovEvent(uint64(m.BlockHeight))
	}
	if m.ChainId != 0 {
		n += 1 + sovEvent(uint64(m.ChainId))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ScheduleCorkEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleCorkEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleCorkEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cork", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cork = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
