// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cork/v2/tx.proto

package v2

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgScheduleCorkRequest - sdk.Msg for scheduling a cork request for on or after a specific block height
type MsgScheduleCorkRequest struct {
	// the scheduled cork
	Cork *Cork `protobuf:"bytes,1,opt,name=cork,proto3" json:"cork,omitempty"`
	// the block height that must be reached
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// signer account address
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgScheduleCorkRequest) Reset()         { *m = MsgScheduleCorkRequest{} }
func (m *MsgScheduleCorkRequest) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleCorkRequest) ProtoMessage()    {}
func (*MsgScheduleCorkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_271bdc677f232222, []int{0}
}
func (m *MsgScheduleCorkRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleCorkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleCorkRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleCorkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleCorkRequest.Merge(m, src)
}
func (m *MsgScheduleCorkRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleCorkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleCorkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleCorkRequest proto.InternalMessageInfo

func (m *MsgScheduleCorkRequest) GetCork() *Cork {
	if m != nil {
		return m.Cork
	}
	return nil
}

func (m *MsgScheduleCorkRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgScheduleCorkRequest) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (*MsgScheduleCorkRequest) XXX_MessageName() string {
	return "cork.v2.MsgScheduleCorkRequest"
}

type MsgScheduleCorkResponse struct {
	// cork ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgScheduleCorkResponse) Reset()         { *m = MsgScheduleCorkResponse{} }
func (m *MsgScheduleCorkResponse) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleCorkResponse) ProtoMessage()    {}
func (*MsgScheduleCorkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271bdc677f232222, []int{1}
}
func (m *MsgScheduleCorkResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleCorkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleCorkResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleCorkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleCorkResponse.Merge(m, src)
}
func (m *MsgScheduleCorkResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleCorkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleCorkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleCorkResponse proto.InternalMessageInfo

func (m *MsgScheduleCorkResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (*MsgScheduleCorkResponse) XXX_MessageName() string {
	return "cork.v2.MsgScheduleCorkResponse"
}
func init() {
	proto.RegisterType((*MsgScheduleCorkRequest)(nil), "cork.v2.MsgScheduleCorkRequest")
	proto.RegisterType((*MsgScheduleCorkResponse)(nil), "cork.v2.MsgScheduleCorkResponse")
}

func init() { proto.RegisterFile("cork/v2/tx.proto", fileDescriptor_271bdc677f232222) }

var fileDescriptor_271bdc677f232222 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x4f, 0xfa, 0x40,
	0x18, 0xc6, 0x39, 0xe0, 0xcf, 0x3f, 0x1c, 0x68, 0xcc, 0xc5, 0x00, 0xe9, 0x70, 0x16, 0x26, 0x64,
	0xe8, 0x1b, 0xeb, 0x60, 0xe2, 0xa8, 0x8b, 0x0b, 0x83, 0x75, 0x73, 0x21, 0xa1, 0x5c, 0xae, 0x15,
	0xca, 0x5b, 0x7b, 0xa5, 0x81, 0xcd, 0xe8, 0x17, 0xf0, 0xa3, 0xf0, 0x31, 0x18, 0x19, 0x1d, 0x4d,
	0x3b, 0xf0, 0x35, 0x4c, 0x8f, 0x6a, 0x4c, 0xd4, 0xe9, 0xde, 0xf7, 0xf7, 0x3c, 0xb9, 0xf7, 0xb9,
	0x7b, 0xe9, 0x91, 0x8b, 0xd1, 0x14, 0x12, 0x1b, 0xe2, 0xa5, 0x15, 0x46, 0x18, 0x23, 0xfb, 0x9f,
	0x13, 0x2b, 0xb1, 0x0d, 0xf6, 0x29, 0x69, 0xa0, 0x45, 0xa3, 0xed, 0xa2, 0x0a, 0x50, 0x41, 0xa0,
	0x24, 0x24, 0x67, 0xf9, 0x51, 0x08, 0xc7, 0x12, 0x25, 0xea, 0x12, 0xf2, 0x6a, 0x4f, 0x7b, 0x2f,
	0x84, 0xb6, 0x86, 0x4a, 0xde, 0xb9, 0x9e, 0x98, 0x2c, 0x66, 0xe2, 0x1a, 0xa3, 0xa9, 0x23, 0x1e,
	0x17, 0x42, 0xc5, 0xac, 0x4b, 0xab, 0xf9, 0xbd, 0x1d, 0x62, 0x92, 0x7e, 0xc3, 0x3e, 0xb0, 0x8a,
	0xa9, 0x96, 0xf6, 0x68, 0x89, 0x75, 0x69, 0x73, 0x3c, 0x43, 0x77, 0x3a, 0xf2, 0x84, 0x2f, 0xbd,
	0xb8, 0x53, 0x36, 0x49, 0xbf, 0xea, 0x34, 0x34, 0xbb, 0xd1, 0x88, 0xb5, 0x68, 0x4d, 0xf9, 0x72,
	0x2e, 0xa2, 0x4e, 0xc5, 0x24, 0xfd, 0xba, 0x53, 0x74, 0x97, 0x8d, 0xe7, 0xdd, 0x7a, 0x50, 0x34,
	0xbd, 0x53, 0xda, 0xfe, 0x11, 0x42, 0x85, 0x38, 0x57, 0x82, 0x1d, 0xd2, 0xb2, 0x3f, 0xd1, 0x19,
	0xea, 0x4e, 0xd9, 0x9f, 0xd8, 0x23, 0x5a, 0x19, 0x2a, 0xc9, 0x6e, 0x69, 0xf3, 0xbb, 0x9d, 0x9d,
	0x7c, 0xc5, 0xfb, 0xfd, 0x35, 0x86, 0xf9, 0xb7, 0x61, 0x3f, 0xc9, 0xf8, 0xf7, 0xb4, 0x5b, 0x0f,
	0xc8, 0xd5, 0x70, 0x93, 0x72, 0xb2, 0x4d, 0x39, 0x79, 0x4f, 0x39, 0x79, 0xcd, 0x78, 0x69, 0x93,
	0x71, 0xb2, 0xcd, 0x78, 0xe9, 0x2d, 0xe3, 0xa5, 0x7b, 0x90, 0x7e, 0xec, 0x2d, 0xc6, 0x96, 0x8b,
	0x01, 0x84, 0x42, 0xca, 0xd5, 0x43, 0x02, 0x0a, 0x83, 0x40, 0xcc, 0x7c, 0x11, 0x41, 0x72, 0x01,
	0x4b, 0xbd, 0x0c, 0x88, 0x57, 0xa1, 0x50, 0x90, 0xd8, 0xe3, 0x9a, 0xfe, 0xe7, 0xf3, 0x8f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x63, 0x3a, 0x3b, 0x37, 0xc7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ScheduleCork(ctx context.Context, in *MsgScheduleCorkRequest, opts ...grpc.CallOption) (*MsgScheduleCorkResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ScheduleCork(ctx context.Context, in *MsgScheduleCorkRequest, opts ...grpc.CallOption) (*MsgScheduleCorkResponse, error) {
	out := new(MsgScheduleCorkResponse)
	err := c.cc.Invoke(ctx, "/cork.v2.Msg/ScheduleCork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ScheduleCork(context.Context, *MsgScheduleCorkRequest) (*MsgScheduleCorkResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ScheduleCork(ctx context.Context, req *MsgScheduleCorkRequest) (*MsgScheduleCorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleCork not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ScheduleCork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgScheduleCorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ScheduleCork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cork.v2.Msg/ScheduleCork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ScheduleCork(ctx, req.(*MsgScheduleCorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cork.v2.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleCork",
			Handler:    _Msg_ScheduleCork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cork/v2/tx.proto",
}

func (m *MsgScheduleCorkRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleCorkRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleCorkRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Cork != nil {
		{
			size, err := m.Cork.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgScheduleCorkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleCorkResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleCorkResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgScheduleCorkRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cork != nil {
		l = m.Cork.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgScheduleCorkResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgScheduleCorkRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleCorkRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleCorkRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cork", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cork == nil {
				m.Cork = &Cork{}
			}
			if err := m.Cork.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgScheduleCorkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleCorkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleCorkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
