name: Unit tests

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test github.com/peggyjv/sommelier/.../x/...
